on: push
name: Test
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.0', '7.1', '7.2', '7.3', '7.3', '8.0' ]

        steps:
            - uses: actions/checkout@master

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install Dependencies
              run: composer install

            - name: Code style check
              run: make code-style-check

            - name: Test
              run: make tests
